FROM node:18 AS build

WORKDIR /app

COPY package.json yarn.lock /app/

RUN yarn install

COPY . /app/
ARG VITE_MODE
ARG VITE_BASE_URL
ARG VITE_ADDRESS_TRC20
ARG VITE_ADDRESS_BEP20
ARG VITE_ADDRESS_SOL
ARG VITE_ADDRESS_ERC20
ARG VITE_SUPPORT_USERNAME
ARG VITE_BOTNAME
ARG VITE_WEBAPPNAME
ARG VITE_SENTRY_AUTH_TOKEN
ARG VITE_SUPPORT_USERNAME
ARG VITE_SENTRY_DSN

RUN yarn build

FROM nginx:alpine AS web
WORKDIR /app

COPY --from=build /app/build ./
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
